/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{tsx,ts}', './src/**/*.stories.tsx'],
  darkMode: ['class', '[data-mode="dark"]'],
  theme: {
    extend: {},
    colors: {
      transparent: 'var(--transparent)',
      // black: 'rgb(var(--black) / <alpha-value>)',
      // white: 'rgb(var(--white) / <alpha-value>)',
      // slate: {
      //   50: 'rgb(var(--slate-50) / <alpha-value>)',
      //   100: 'rgb(var(--slate-100) / <alpha-value>)',
      //   200: 'rgb(var(--slate-200) / <alpha-value>)',
      //   300: 'rgb(var(--slate-300) / <alpha-value>)',
      //   400: 'rgb(var(--slate-400) / <alpha-value>)',
      //   500: 'rgb(var(--slate-500) / <alpha-value>)',
      //   600: 'rgb(var(--slate-600) / <alpha-value>)',
      //   700: 'rgb(var(--slate-700) / <alpha-value>)',
      //   800: 'rgb(var(--slate-800) / <alpha-value>)',
      //   900: 'rgb(var(--slate-900) / <alpha-value>)',
      //   950: 'rgb(var(--slate-950) / <alpha-value>)',
      // },
      gray: {
        50: 'rgb(var(--gray-50) / <alpha-value>)',
        100: 'rgb(var(--gray-100) / <alpha-value>)',
        200: 'rgb(var(--gray-200) / <alpha-value>)',
        300: 'rgb(var(--gray-300) / <alpha-value>)',
        400: 'rgb(var(--gray-400) / <alpha-value>)',
        500: 'rgb(var(--gray-500) / <alpha-value>)',
        600: 'rgb(var(--gray-600) / <alpha-value>)',
        700: 'rgb(var(--gray-700) / <alpha-value>)',
        800: 'rgb(var(--gray-800) / <alpha-value>)',
        900: 'rgb(var(--gray-900) / <alpha-value>)',
        950: 'rgb(var(--gray-950) / <alpha-value>)',
      },
      // zinc: {
      //   50: 'rgb(var(--zinc-50) / <alpha-value>)',
      //   100: 'rgb(var(--zinc-100) / <alpha-value>)',
      //   200: 'rgb(var(--zinc-200) / <alpha-value>)',
      //   300: 'rgb(var(--zinc-300) / <alpha-value>)',
      //   400: 'rgb(var(--zinc-400) / <alpha-value>)',
      //   500: 'rgb(var(--zinc-500) / <alpha-value>)',
      //   600: 'rgb(var(--zinc-600) / <alpha-value>)',
      //   700: 'rgb(var(--zinc-700) / <alpha-value>)',
      //   800: 'rgb(var(--zinc-800) / <alpha-value>)',
      //   900: 'rgb(var(--zinc-900) / <alpha-value>)',
      //   950: 'rgb(var(--zinc-950) / <alpha-value>)',
      // },
      // neutral: {
      //   50: 'rgb(var(--neutral-50) / <alpha-value>)',
      //   100: 'rgb(var(--neutral-100) / <alpha-value>)',
      //   200: 'rgb(var(--neutral-200) / <alpha-value>)',
      //   300: 'rgb(var(--neutral-300) / <alpha-value>)',
      //   400: 'rgb(var(--neutral-400) / <alpha-value>)',
      //   500: 'rgb(var(--neutral-500) / <alpha-value>)',
      //   600: 'rgb(var(--neutral-600) / <alpha-value>)',
      //   700: 'rgb(var(--neutral-700) / <alpha-value>)',
      //   800: 'rgb(var(--neutral-800) / <alpha-value>)',
      //   900: 'rgb(var(--neutral-900) / <alpha-value>)',
      //   950: 'rgb(var(--neutral-950) / <alpha-value>)',
      // },
      // stone: {
      //   50: 'rgb(var(--stone-50) / <alpha-value>)',
      //   100: 'rgb(var(--stone-100) / <alpha-value>)',
      //   200: 'rgb(var(--stone-200) / <alpha-value>)',
      //   300: 'rgb(var(--stone-300) / <alpha-value>)',
      //   400: 'rgb(var(--stone-400) / <alpha-value>)',
      //   500: 'rgb(var(--stone-500) / <alpha-value>)',
      //   600: 'rgb(var(--stone-600) / <alpha-value>)',
      //   700: 'rgb(var(--stone-700) / <alpha-value>)',
      //   800: 'rgb(var(--stone-800) / <alpha-value>)',
      //   900: 'rgb(var(--stone-900) / <alpha-value>)',
      //   950: 'rgb(var(--stone-950) / <alpha-value>)',
      // },
      red: {
        50: 'rgb(var(--red-50) / <alpha-value>)',
        100: 'rgb(var(--red-100) / <alpha-value>)',
        200: 'rgb(var(--red-200) / <alpha-value>)',
        300: 'rgb(var(--red-300) / <alpha-value>)',
        400: 'rgb(var(--red-400) / <alpha-value>)',
        500: 'rgb(var(--red-500) / <alpha-value>)',
        600: 'rgb(var(--red-600) / <alpha-value>)',
        700: 'rgb(var(--red-700) / <alpha-value>)',
        800: 'rgb(var(--red-800) / <alpha-value>)',
        900: 'rgb(var(--red-900) / <alpha-value>)',
        950: 'rgb(var(--red-950) / <alpha-value>)',
      },
      // orange: {
      //   50: 'rgb(var(--orange-50) / <alpha-value>)',
      //   100: 'rgb(var(--orange-100) / <alpha-value>)',
      //   200: 'rgb(var(--orange-200) / <alpha-value>)',
      //   300: 'rgb(var(--orange-300) / <alpha-value>)',
      //   400: 'rgb(var(--orange-400) / <alpha-value>)',
      //   500: 'rgb(var(--orange-500) / <alpha-value>)',
      //   600: 'rgb(var(--orange-600) / <alpha-value>)',
      //   700: 'rgb(var(--orange-700) / <alpha-value>)',
      //   800: 'rgb(var(--orange-800) / <alpha-value>)',
      //   900: 'rgb(var(--orange-900) / <alpha-value>)',
      //   950: 'rgb(var(--orange-950) / <alpha-value>)',
      // },
      amber: {
        50: 'rgb(var(--amber-50) / <alpha-value>)',
        100: 'rgb(var(--amber-100) / <alpha-value>)',
        200: 'rgb(var(--amber-200) / <alpha-value>)',
        300: 'rgb(var(--amber-300) / <alpha-value>)',
        400: 'rgb(var(--amber-400) / <alpha-value>)',
        500: 'rgb(var(--amber-500) / <alpha-value>)',
        600: 'rgb(var(--amber-600) / <alpha-value>)',
        700: 'rgb(var(--amber-700) / <alpha-value>)',
        800: 'rgb(var(--amber-800) / <alpha-value>)',
        900: 'rgb(var(--amber-900) / <alpha-value>)',
        950: 'rgb(var(--amber-950) / <alpha-value>)',
      },
      // yellow: {
      //   50: 'rgb(var(--yellow-50) / <alpha-value>)',
      //   100: 'rgb(var(--yellow-100) / <alpha-value>)',
      //   200: 'rgb(var(--yellow-200) / <alpha-value>)',
      //   300: 'rgb(var(--yellow-300) / <alpha-value>)',
      //   400: 'rgb(var(--yellow-400) / <alpha-value>)',
      //   500: 'rgb(var(--yellow-500) / <alpha-value>)',
      //   600: 'rgb(var(--yellow-600) / <alpha-value>)',
      //   700: 'rgb(var(--yellow-700) / <alpha-value>)',
      //   800: 'rgb(var(--yellow-800) / <alpha-value>)',
      //   900: 'rgb(var(--yellow-900) / <alpha-value>)',
      //   950: 'rgb(var(--yellow-950) / <alpha-value>)',
      // },
      // lime: {
      //   50: 'rgb(var(--lime-50) / <alpha-value>)',
      //   100: 'rgb(var(--lime-100) / <alpha-value>)',
      //   200: 'rgb(var(--lime-200) / <alpha-value>)',
      //   300: 'rgb(var(--lime-300) / <alpha-value>)',
      //   400: 'rgb(var(--lime-400) / <alpha-value>)',
      //   500: 'rgb(var(--lime-500) / <alpha-value>)',
      //   600: 'rgb(var(--lime-600) / <alpha-value>)',
      //   700: 'rgb(var(--lime-700) / <alpha-value>)',
      //   800: 'rgb(var(--lime-800) / <alpha-value>)',
      //   900: 'rgb(var(--lime-900) / <alpha-value>)',
      //   950: 'rgb(var(--lime-950) / <alpha-value>)',
      // },
      // green: {
      //   50: 'rgb(var(--green-50) / <alpha-value>)',
      //   100: 'rgb(var(--green-100) / <alpha-value>)',
      //   200: 'rgb(var(--green-200) / <alpha-value>)',
      //   300: 'rgb(var(--green-300) / <alpha-value>)',
      //   400: 'rgb(var(--green-400) / <alpha-value>)',
      //   500: 'rgb(var(--green-500) / <alpha-value>)',
      //   600: 'rgb(var(--green-600) / <alpha-value>)',
      //   700: 'rgb(var(--green-700) / <alpha-value>)',
      //   800: 'rgb(var(--green-800) / <alpha-value>)',
      //   900: 'rgb(var(--green-900) / <alpha-value>)',
      //   950: 'rgb(var(--green-950) / <alpha-value>)',
      // },
      // emerald: {
      //   50: 'rgb(var(--emerald-50) / <alpha-value>)',
      //   100: 'rgb(var(--emerald-100) / <alpha-value>)',
      //   200: 'rgb(var(--emerald-200) / <alpha-value>)',
      //   300: 'rgb(var(--emerald-300) / <alpha-value>)',
      //   400: 'rgb(var(--emerald-400) / <alpha-value>)',
      //   500: 'rgb(var(--emerald-500) / <alpha-value>)',
      //   600: 'rgb(var(--emerald-600) / <alpha-value>)',
      //   700: 'rgb(var(--emerald-700) / <alpha-value>)',
      //   800: 'rgb(var(--emerald-800) / <alpha-value>)',
      //   900: 'rgb(var(--emerald-900) / <alpha-value>)',
      //   950: 'rgb(var(--emerald-950) / <alpha-value>)',
      // },
      teal: {
        50: 'rgb(var(--teal-50) / <alpha-value>)',
        100: 'rgb(var(--teal-100) / <alpha-value>)',
        200: 'rgb(var(--teal-200) / <alpha-value>)',
        300: 'rgb(var(--teal-300) / <alpha-value>)',
        400: 'rgb(var(--teal-400) / <alpha-value>)',
        500: 'rgb(var(--teal-500) / <alpha-value>)',
        600: 'rgb(var(--teal-600) / <alpha-value>)',
        700: 'rgb(var(--teal-700) / <alpha-value>)',
        800: 'rgb(var(--teal-800) / <alpha-value>)',
        900: 'rgb(var(--teal-900) / <alpha-value>)',
        950: 'rgb(var(--teal-950) / <alpha-value>)',
      },
      // cyan: {
      //   50: 'rgb(var(--cyan-50) / <alpha-value>)',
      //   100: 'rgb(var(--cyan-100) / <alpha-value>)',
      //   200: 'rgb(var(--cyan-200) / <alpha-value>)',
      //   300: 'rgb(var(--cyan-300) / <alpha-value>)',
      //   400: 'rgb(var(--cyan-400) / <alpha-value>)',
      //   500: 'rgb(var(--cyan-500) / <alpha-value>)',
      //   600: 'rgb(var(--cyan-600) / <alpha-value>)',
      //   700: 'rgb(var(--cyan-700) / <alpha-value>)',
      //   800: 'rgb(var(--cyan-800) / <alpha-value>)',
      //   900: 'rgb(var(--cyan-900) / <alpha-value>)',
      //   950: 'rgb(var(--cyan-950) / <alpha-value>)',
      // },
      // sky: {
      //   50: 'rgb(var(--sky-50) / <alpha-value>)',
      //   100: 'rgb(var(--sky-100) / <alpha-value>)',
      //   200: 'rgb(var(--sky-200) / <alpha-value>)',
      //   300: 'rgb(var(--sky-300) / <alpha-value>)',
      //   400: 'rgb(var(--sky-400) / <alpha-value>)',
      //   500: 'rgb(var(--sky-500) / <alpha-value>)',
      //   600: 'rgb(var(--sky-600) / <alpha-value>)',
      //   700: 'rgb(var(--sky-700) / <alpha-value>)',
      //   800: 'rgb(var(--sky-800) / <alpha-value>)',
      //   900: 'rgb(var(--sky-900) / <alpha-value>)',
      //   950: 'rgb(var(--sky-950) / <alpha-value>)',
      // },
      // blue: {
      //   50: 'rgb(var(--blue-50) / <alpha-value>)',
      //   100: 'rgb(var(--blue-100) / <alpha-value>)',
      //   200: 'rgb(var(--blue-200) / <alpha-value>)',
      //   300: 'rgb(var(--blue-300) / <alpha-value>)',
      //   400: 'rgb(var(--blue-400) / <alpha-value>)',
      //   500: 'rgb(var(--blue-500) / <alpha-value>)',
      //   600: 'rgb(var(--blue-600) / <alpha-value>)',
      //   700: 'rgb(var(--blue-700) / <alpha-value>)',
      //   800: 'rgb(var(--blue-800) / <alpha-value>)',
      //   900: 'rgb(var(--blue-900) / <alpha-value>)',
      //   950: 'rgb(var(--blue-950) / <alpha-value>)',
      // },
      // indigo: {
      //   50: 'rgb(var(--indigo-50) / <alpha-value>)',
      //   100: 'rgb(var(--indigo-100) / <alpha-value>)',
      //   200: 'rgb(var(--indigo-200) / <alpha-value>)',
      //   300: 'rgb(var(--indigo-300) / <alpha-value>)',
      //   400: 'rgb(var(--indigo-400) / <alpha-value>)',
      //   500: 'rgb(var(--indigo-500) / <alpha-value>)',
      //   600: 'rgb(var(--indigo-600) / <alpha-value>)',
      //   700: 'rgb(var(--indigo-700) / <alpha-value>)',
      //   800: 'rgb(var(--indigo-800) / <alpha-value>)',
      //   900: 'rgb(var(--indigo-900) / <alpha-value>)',
      //   950: 'rgb(var(--indigo-950) / <alpha-value>)',
      // },
      violet: {
        50: 'rgb(var(--violet-50) / <alpha-value>)',
        100: 'rgb(var(--violet-100) / <alpha-value>)',
        200: 'rgb(var(--violet-200) / <alpha-value>)',
        300: 'rgb(var(--violet-300) / <alpha-value>)',
        400: 'rgb(var(--violet-400) / <alpha-value>)',
        500: 'rgb(var(--violet-500) / <alpha-value>)',
        600: 'rgb(var(--violet-600) / <alpha-value>)',
        700: 'rgb(var(--violet-700) / <alpha-value>)',
        800: 'rgb(var(--violet-800) / <alpha-value>)',
        900: 'rgb(var(--violet-900) / <alpha-value>)',
        950: 'rgb(var(--violet-950) / <alpha-value>)',
      },
      // purple: {
      //   50: 'rgb(var(--purple-50) / <alpha-value>)',
      //   100: 'rgb(var(--purple-100) / <alpha-value>)',
      //   200: 'rgb(var(--purple-200) / <alpha-value>)',
      //   300: 'rgb(var(--purple-300) / <alpha-value>)',
      //   400: 'rgb(var(--purple-400) / <alpha-value>)',
      //   500: 'rgb(var(--purple-500) / <alpha-value>)',
      //   600: 'rgb(var(--purple-600) / <alpha-value>)',
      //   700: 'rgb(var(--purple-700) / <alpha-value>)',
      //   800: 'rgb(var(--purple-800) / <alpha-value>)',
      //   900: 'rgb(var(--purple-900) / <alpha-value>)',
      //   950: 'rgb(var(--purple-950) / <alpha-value>)',
      // },
      fuchsia: {
        50: 'rgb(var(--fuchsia-50) / <alpha-value>)',
        100: 'rgb(var(--fuchsia-100) / <alpha-value>)',
        200: 'rgb(var(--fuchsia-200) / <alpha-value>)',
        300: 'rgb(var(--fuchsia-300) / <alpha-value>)',
        400: 'rgb(var(--fuchsia-400) / <alpha-value>)',
        500: 'rgb(var(--fuchsia-500) / <alpha-value>)',
        600: 'rgb(var(--fuchsia-600) / <alpha-value>)',
        700: 'rgb(var(--fuchsia-700) / <alpha-value>)',
        800: 'rgb(var(--fuchsia-800) / <alpha-value>)',
        900: 'rgb(var(--fuchsia-900) / <alpha-value>)',
        950: 'rgb(var(--fuchsia-950) / <alpha-value>)',
      },
      // pink: {
      //   50: 'rgb(var(--pink-50) / <alpha-value>)',
      //   100: 'rgb(var(--pink-100) / <alpha-value>)',
      //   200: 'rgb(var(--pink-200) / <alpha-value>)',
      //   300: 'rgb(var(--pink-300) / <alpha-value>)',
      //   400: 'rgb(var(--pink-400) / <alpha-value>)',
      //   500: 'rgb(var(--pink-500) / <alpha-value>)',
      //   600: 'rgb(var(--pink-600) / <alpha-value>)',
      //   700: 'rgb(var(--pink-700) / <alpha-value>)',
      //   800: 'rgb(var(--pink-800) / <alpha-value>)',
      //   900: 'rgb(var(--pink-900) / <alpha-value>)',
      //   950: 'rgb(var(--pink-950) / <alpha-value>)',
      // },
      // rose: {
      //   50: 'rgb(var(--rose-50) / <alpha-value>)',
      //   100: 'rgb(var(--rose-100) / <alpha-value>)',
      //   200: 'rgb(var(--rose-200) / <alpha-value>)',
      //   300: 'rgb(var(--rose-300) / <alpha-value>)',
      //   400: 'rgb(var(--rose-400) / <alpha-value>)',
      //   500: 'rgb(var(--rose-500) / <alpha-value>)',
      //   600: 'rgb(var(--rose-600) / <alpha-value>)',
      //   700: 'rgb(var(--rose-700) / <alpha-value>)',
      //   800: 'rgb(var(--rose-800) / <alpha-value>)',
      //   900: 'rgb(var(--rose-900) / <alpha-value>)',
      //   950: 'rgb(var(--rose-950) / <alpha-value>)',
      // },
    }
  },
  plugins: [],
};
